### ISSUE TITLE
Include test failure time in Fail message

### ISSUE THREAD

**Issue by billt-hlit** [AMWA-TV/nmos-testing#104]
Should be an easy enhancement -- append str(datetime.now().time()) to the end of the failure details? This change would help debugging by making it possible to correlate the test failure with the any log messages from the system under test.

**Comment by garethsb-sony** [comment]
I think this is a great idea. I'm a bit concerned that it's not possible to do accurately for test cases that e.g. use ``do_registry_basics_prereqs`` in IS0401Test.py, because the pertinent time would be the timestamp on the request/response that resulted in the the failure, not the time that the test looked through those?

**Comment by billt-hlit** [comment]
"Le mieux est l'ennemi du bien." Even a rough timestamp would help narrow down a search. Refinements can be added later.

**Comment by andrewbonney** [comment]
Added a basic solution for this in https://github.com/AMWA-TV/nmos-testing/pull/122. It obviously suffers from the issue that Gareth highlighted, so I'm not sure if it should be accompanied by a warning about the accuracy of the time shown somewhere?
