### ISSUE TITLE
IS-04-01 test_12 dependency? 

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#212]
Test 12 in the Node API suite checks that there are no 'ver_' TXT records in registered operation.

But obviously this relies on a Registry being enabled, which as far as we can see isn't ensured by this test itself, so it's only likely to pass currently if run sufficiently soon after one of the tests that does. 

Should it do something similar to `test_21` do you think, @andrewbonney?

We'd like to make `do_registry_basics_prereqs` wait for a bit after the last registry is disabled (like it does after all the others) in order to make `test_21` reliable, but that will make `test_12` always fail right now.

**Comment by garethsb-sony** [comment]
Hmm, `test_12` should also have the check for `ENABLE_DNS_SD` and `DNS_SD_MODE` being multicast, right?

**Comment by andrewbonney** [comment]
Yeah, looks like there's a missing dependency here at present, but it would be nice to resolve without adding '@test_depends'. I think adding an explicit registry advert and some sort of timeout for it to be noticed would make sense.

The reason test_12 doesn't reference the config variables is because they're intended to relate to disruptive advertisements rather than browsing which shouldn't be disruptive on a network (see https://github.com/AMWA-TV/nmos-testing/blob/master/Config.py#L15). Given that the resolution will likely involve an advertisement however they will need to be checked.

**Comment by garethsb-sony** [comment]
> The reason test_12 doesn't reference the config variables is

That makes sense, but as you're saying, `test_12` can only expect the Node API under test to go into registered mode if the test starts and advertises a Registry?

**Comment by andrewbonney** [comment]
Yes, absolutely. I haven't checked the history but it may simply be that a @test_depends was never added when it became possible to run tests individually. This would previously have been covered by the registry prereqs method.

**Comment by garethsb-sony** [comment]
Except that since the prereqs end up by disabling all the registries, if you don't run `test_12` fast enough, there's a race condition as the Node may have already noticed and resumed peer-to-peer operation.

**Comment by andrewbonney** [comment]
Yes, good point
