### ISSUE TITLE
IS-04-01 test_05 may incorrectly report successful heartbeats

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#333]
When performing the bulk of the IS-04-01 tests, various mock registries are enabled and interactions with them recorded. In one case I have observed, when the primary registry is enabled a Node first issued a heartbeat to it and received a 404 code. The Node then registered all of its resources before issuing its next heartbeat. Following this, a further heartbeat was issued, but at the wrong frequency. This should have been caught by `test_05`, but because two heartbeats had already been recorded, the third one happened after the primary registry had been disabled.

The code expects that heartbeats will only be recorded by the mock registry if a Node was already registered, but currently they are recorded whether a Node was registered or not.

This is definitely an edge case, but the failure to catch it makes it much harder to debug the registry failover tests like `test_15` and `test_16`.

**Comment by andrewbonney** [comment]
See https://github.com/AMWA-TV/nmos-testing/tree/issue333-opt1 and https://github.com/AMWA-TV/nmos-testing/tree/issue333-opt2

**Comment by JamesGibo** [comment]
The opposite is also possible, where test_05 may incorrectly report a failure with heartbeats too frequent.
If a Node first sends a heartbeat before it is registered, then registers and heartbeats, test_05 will report that heartbeats are too frequent. 
This is caused by the Mock registry counting all heartbeats, even if they result in a HTTP 404.
