### ISSUE TITLE
IS0402 - test_22_1 for v1.1

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-testing#390]
I just stumbled upon a potential problem while executing test_22_1 _Query API subscriptions resource does not support downgrade queries_ for v1.1.

During the test there comes the point where `# Generate a subscription at the API version under test and the version below that`. For v1.1 this means, a v1.0 subscription is requested. Now inside the `resp_json = self.post_subscription(test, sub_json, query_url=query_sub_url)` the request is done against `/v1.0`, but the used schema for validation is versioned with `v1.1` (as this is the current version under test).

This is of course wrong (and fails because the `v1.0` subscription response is missing the `secure` key (which is only included in v1.1 and higher)).

I slightly remember we had already the requirement where we did a schema validation against a version which is not the current version under test - but I can't remember where that was. Do we already support this? Maybe I overlooked that.

**Comment by garethsb-sony** [comment]
We don't have the means to validate against schemas other than the version under test (because the test suite only checks out one branch of the spec repo at a time).

I've worked around with this elsewhere (I think) by simply not doing the schema validation if it's not for the version under test. I'll have a look.
