### ISSUE TITLE
IS-04-01 test_21 the mock registry does not return location header

### ISSUE THREAD

**Issue by JamesGibo** [AMWA-TV/nmos-testing#396]
During test_21, the mock registry returns a HTTP 200 when trying to register, the node should then perform a DELETE using the location header in the response, but the header is missing from the 200 response

**Comment by garethsb-sony** [comment]
True.

FWIW, if it's a 200 OK response, the Node should always be able to determine the URL itself based on the POST request data. Since v1.3, if it's a 409 Conflict response, the use of the Location header may be necessary e.g. if the Node is recovering from a reboot and doesn't know its previously registered API version. 

I don't think we have any 409 testing yet...
