### ISSUE TITLE
not specifying charset in Content-Type may be a security error

### ISSUE THREAD

**Issue by thosil** [AMWA-TV/nmos-testing#399]
Current behavior:
-----------------------
The node 3 test in IS-04 reports a warning if the Node API reply header Content-Type specify a charset.

Issue:
--------
Node API Implementations using node.js Express can't reply an "application/json" content type without specifying the charset, because it has been reported that not specifying it could lead to a security breach: https://www.npmjs.com/advisories/8 .

Desired behavior:
-----------------------
Report an error if charset is present and not "utf-8".

**Comment by garethsb-sony** [comment]
So far as I can tell, the IANA registration for `application/json` (updated in 2017) still says `No "charset" parameter is defined for this registration.` ([reference](https://www.iana.org/assignments/media-types/application/json))

The concern with no charset appears to derive from XSS attacks based on browsers using content type sniffing and misidentifying the content as UTF-7. However, no modern browsers do this. Chrome and Firefox haven't supported UTF-7 at all since 2009 and 2011 respectively ([refererence](http://michaelthelin.se/security/2014/06/08/web-security-cross-site-scripting-attacks-using-utf-7.html)). Perhaps Internet Explorer still does, but only if explicitly added, it hasn't done content sniffing for UTF-7 since IE7 ([reference](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/dd565635(v=vs.85)?redirectedfrom=MSDN)).

**Comment by thosil** [comment]
@garethsb-sony  I agree with you, we shouldn't be affected by this problem.
I tried to open a new issue in the express.js (which was closed a couple of minutes after it was opened).
Finally I found a (working) workaround.
This issue can be closed :-)
