### ISSUE TITLE
IS-05-01: should test_09_01 set master_enable to true?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-testing#503]
Follow-up to #434.

`IS0501Test.test_09_01` checks that all params listed in **/single/senders/{senderId}/active** match their corresponding SDP files.

If the sender is disabled however, it reports FAIL when the **/transportfile** resource returns a 404.

Should this be a FAIL? Or WARNING/UNCLEAR?
Or should it set `"master_enable": true` before performing the test?

**Comment by garethsb-sony** [comment]
Maybe the same applies to `IS0502Test.test_14`-`test_17`?

**Comment by firthmj** [comment]
This issue is still present. The IS-05 spec explicitly allows implementations to return a 404 if the master_enable is set to false, so compliant implementations can fail the test suite because of this issue

**Comment by garethsb** [comment]
To work around this, make sure all Senders are enabled.

**Comment by alabou** [comment]
Is there any plan to fix this issue or remove test_09_01 from the test suite?

**Comment by alabou** [comment]
The issue I see is that other tests requiring master_enable set to true identify the problem and report a message indicating to do so ... But test_09 is not checking master_enable and simply fail if it gets 404 ... which I think is bad because this is a test error. I think the test should behave according to the NMOS specifications and accept 404 if master_enable is not true. 

The test operator can know that test-09 fail because of that and enable the sender and rerun the test ... but this is asking the test operator to fix a test suite bug. I don't think it is a good idea to have test operators or implementations attempt to work around tests suite problems.

**Comment by garethsb** [comment]
I don't think it can just accept `404` and report a PASS in the case that `master_enable` is not true, because that could mask errors. So, we could report UNCLEAR... or we have to actually activate the Sender. But then we are testing two things... what do you think is right?

**Comment by alabou** [comment]
Here is what I get for test_41 and test_42 that require master_enable with test suite IS-05-01

"test_41 .............. Could Not Test
One or more of the tested transport files returned a 404 HTTP code. Please ensure 'master_enable' is set to true for all Senders and re-test.
test_42 .............. Could Not Test
One or more of the tested transport files returned a 404 HTTP code. Please ensure 'master_enable' is set to true for all Senders and re-test."

So if the rule is to ask the user to manually set master_enable then the same approach could be taken. Otherwise a warning indicating that test_09_01 could not run because master_enable is false would do the job. Currently test_09_01 produces a failure which is bad.
