### ISSUE TITLE
DNS TTL interferes with IS-04 tests

### ISSUE THREAD

**Issue by wsneijers** [AMWA-TV/nmos-testing#509]
Hello,

When running the testing tool in unicast mode the default TTL of the DNS zones (60 seconds) has a negative impact on the test(s). For me, at the moment it is only test 21. But there could be others as well. 

If I run it with defaults:

![image](https://user-images.githubusercontent.com/10929317/76199731-b41bfd80-61f0-11ea-96fb-25fa9df4cfd0.png)

If I then change the TTL (`test_data/core/dns_base.zone`) to 1 second:

![image](https://user-images.githubusercontent.com/10929317/76199798-d150cc00-61f0-11ea-8b83-22f17cf5fae4.png)

Is it a good fix to just lower the number?

**Comment by garethsb-sony** [comment]
Hmm... @andrewbonney had experimented in this area: https://github.com/AMWA-TV/nmos-testing/pull/228

**Comment by andrewbonney** [comment]
This sounds like a subtly different problem to what I was working on. My intention was to use a low TTL in order to force the Node to perform queries more frequently than it would otherwise have done, and so avoid some potential need to restart devices during testing.

Assuming this device is passing test_02 in the same test run, it seems very odd that it is then failing test_21 for DNS reasons. Whether a re-query is performed or not, the registry address for this test should always resolve to the same thing. I'm wondering if the after effects of something like test_16_01 may be to blame?

@wsneijers could you confirm if your Node is failing any other tests before test_21, and if so which ones? Perhaps you could also run test_21 in isolation to see if the same result is seen with the original TTL?

**Comment by wsneijers** [comment]
Sure,

It does pass test_02. If I run the test isolated it has the same behavior. 

Also I'm struggling with test 15 and 16 in unicast mode. But I don't think it has something to do with this issue. Unless both are failing because of similar reasons.

**Comment by andrewbonney** [comment]
Hmm. I'd like to get to the bottom of it as just changing the TTL sounds like it will just cause the issue to recur in a different place/way later on. Could you perhaps share the console output from your full test run, which should include an indication of when DNS queries and responses occur? Feel free to e-mail it as it'll probably be a bit big to include here.

**Comment by wsneijers** [comment]
Sorry for the long delay. I have spent a lot of time figuring out what went wrong. In the end it ended up being an issue between [sony nmos](https://github.com/sony/nmos-cpp) and avahi. I am now able to pass all the unicast tests. For reference [here](https://github.com/sony/nmos-cpp/issues/128) is the issue explaining in more detail what goes wrong. Thanks for the help!

**Comment by andrewbonney** [comment]
No problem, sounds like it was quite involved!
