### ISSUE TITLE
[IS-05-01] Uncaught Exception in generate_destination_ports when destination_port in constraints is an empty list (test_23)

### ISSUE THREAD

**Issue by pimiller** [AMWA-TV/nmos-testing#631]
While I understand that having an empty list for a constraint is not valid, it is causing the following exception:

  File "/root/nmos-test/nmos-testing/nmostesting/GenericTest.py", line 162, in execute_test
    self.result.append(method(test))
  File "/root/nmos-test/nmos-testing/nmostesting/suites/IS0501Test.py", line 531, in test_23
    self.transport_types[sender])
  File "/root/nmos-test/nmos-testing/nmostesting/IS05Utils.py", line 307, in generate_changeable_param
    return self.generate_destination_ports(port, portId)
  File "/root/nmos-test/nmos-testing/nmostesting/IS05Utils.py", line 329, in generate_destination_ports
    toReturn.append(values[randint(0, len(values) - 1)])
  File "/usr/lib64/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/usr/lib64/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
 * Test results written to file: result.xml
 * Exiting

For this specific case, the sender's destination_port constraint was (incorrectly) defined as follows:
        "destination_port": {
            "enum": []
        },

**Comment by garethsb** [comment]
Thanks for the report.

This reveals that the JSON Schemas have a slight flaw, because I expected your example JSON to fail test `auto_connection_18` (`GET /x-nmos/connection/v1.1/single/senders/{senderId}/constraints`) due to schema violation, and it doesn't. The flaw is very similar to one that was fixed for the `/staged` response previously - https://github.com/AMWA-TV/nmos-device-connection-management/pull/99. We'll get this sorted in **v1.1.x**.

That said, I completely agree that even if `auto_connection_18` had reported the violation, the subsequent tests (`test_23`, `test_25`, `test_27`, `test_29`, `test_36`) ought to be failures not exceptions. We'll fix that.
