### ISSUE TITLE
IS-05 /transportfile signalled an unnecessary 'charset' in its Content-Type

### ISSUE THREAD

**Issue by adoussot** [AMWA-TV/nmos-testing#651]
Hi, 

First of all, thank you very much for your project. It is really helpful to design an NMOS workflow. I'm writing this issue since I don't understanding the meaning of the [IS-05-014test42](https://github.com/AMWA-TV/nmos-testing/commit/16d898c2d281445290afe1b68a859336d882bbbf). Why it fails if we are adding a `charset=utf-8` in the Content-Type header ?

![image](https://user-images.githubusercontent.com/6343558/156391258-c1f0006f-d0b0-4b3a-a835-79cc52a763d9.png)

> API signalled an unnecessary 'charset' in its Content-Type: application/sdp; charset=utf-8

The receiver need to know which charset was used to encode the text (even if the SDP RFC says it's utf-8/ by default https://datatracker.ietf.org/doc/html/rfc8866) 

yours sincerelly

**Comment by garethsb** [comment]
Hi @adoussot.

The RFC and IANA media type registration actually say that there are no required or optional parameters permitted for `application/sdp`, i.e. not even `charset`.

The reason the SDP spec says that is because most SDP data are ALWAYS in UTF-8, and then the `a=charset:` attribute can change the character set just for certain values. SDP data converted into a different character set is not valid SDP data.

Hence the test case follows the specification.

**Comment by adoussot** [comment]
Thank you very much for your answer !
