### ISSUE TITLE
IS-04: Appropriate length of timeout after advertising the NMOS Test Suite Registration API?

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#7]
``test_01`` in IS0401Test only allows 5 seconds for initial registration. The comment implies this is something to do with the default heartbeat interval, which doesn't make any sense to me...

**Comment by andrewbonney** [comment]
The check as it stands is intended to wait until at least 5 seconds have elapsed since the last resource was registered with the Registration API (in order to ensure we catch all of the Node's resources). This is set to 5 to ensure at least one heartbeat at the default interval is caught following a Node /self registration.

The issue is that the method as a whole is based upon the assumption that a Node will register as soon as it sees a Registration API appear via mDNS given that there weren't any previously. This may not be a valid assumption for all implementations.

Could you suggest a time that might be suitable to wait for a registration to occur after first mDNS advertisement? There is a trade-off here as whilst we can exit this test early if a Node successfully registers, it will wait for this time in full if the Node fails to register, and as a result the test results page will take longer to present itself.

**Comment by garethsb-sony** [comment]
> The check as it stands is intended to wait until at least 5 seconds have elapsed since the last resource was registered with the Registration API (in order to ensure we catch all of the Node's resources). This is set to 5 to ensure at least one heartbeat at the default interval is caught following a Node /self registration.

That confuses me.
Why are we waiting for _all_ resources to be registered in ``test_01`` rather than just the Node /self resource?
Why are we waiting for heartbeats in ``test_01``? And if heartbeating is important here, shouldn't it be 5 seconds after the Node /self resource is registered, not the last resource?

Anyway, as you explained, that wasn't actually my issue...

> The issue is that the method as a whole is based upon the assumption that a Node will register as soon as it sees a Registration API appear via mDNS given that there weren't any previously. This may not be a valid assumption for all implementations.

I'm not sure. The IS-04 documentation mentions exponential back-off after failures during registered operation, but doesn't specify this in detail, e.g. a cap/limit. And during peer-to-peer operation, it doesn't say anything about how quickly a newly DNS-SD advertised Registry should be discovered.

What do you think is reasonable?
